version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-bookeasy
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    command: npm run dev
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:123456@db:5432/db_bookeasy

  db:
    image: postgres:15-alpine
    container_name: db-bookeasy
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db_bookeasy

volumes:
  pgdata:
